### ISSUE TITLE
Skip intercept downlload for those file generate by javascript

### ISSUE THREAD

**Issue by LancelotLewis** [alexhua/Aria2-for-chrome#50]
**Describe the bug**

There is some website generate file by javascript and output this file, let broswer to download it, but those file can't be donwload by aria2, those file should skip by Aria2-for-chorme

**To Reproduce**
1. Go to 'https://lab.sorz.org/tools/asstosrt/'
2. Choose file
3. convert and download

**Expected behavior**

While download file generate by javascript(not a true url link), don't intercept the download, use broswer to download it

**Desktop (please complete the following information):**
 - OS: win10 x64
 - Browser Edge chromuim
 - Version  86.0.622.58

**Comment by alexhua** [comment]
Thanks for your feedback.

1. I cannot reproduece the bahavior from your url. The browser just displayed the srt file directly, because the file mime type is text. And there was no download happened. 
2. Lots of cloud storage performs like this. So I think it is necessary to intercept the download triggered by JS.
