### ISSUE TITLE
How can I save settings?

### ISSUE THREAD

**Issue by candrapersada** [alexhua/Aria2-for-chrome#53]
I run aria2, then I open AriaNG native, change some advanced settings etc..
Then I close ariang and aria2
When I open them again, all my settings are gone.
How can I make these settings permanent?
I thought maybe "Save session" button would do it but whenever I click it, it says "Filename is not given"
What does that mean? There's no input to give a filename or anything, it always give that error.

Using Windows btw and Linux.

Can you help please? Thanks!

**Comment by alexhua** [comment]
You should build up a config file mannually and specify it to aria2 as start-up parameter just like "aria2c.exe --conf-path=aria2.conf ".  You can also Google a config template and edit it as you need.
Any further infomation, please refer to https://aria2.github.io/manual/en/html/

**Comment by candrapersada** [comment]
how to copy aria2 from AriraNg settings, paste it into aria2.conf or create a new aria2.conf?

**Comment by alexhua** [comment]
> how to copy aria2 from AriraNg settings, paste it into aria2.conf or create a new AriaNg.conf?
This extension is just a bridge among browser, AriaNG and aria2c. This issue is already out of range of this extension.

About aria2 issue, you can access https://github.com/aria2/aria2/issues.
About AriaNG issue, you can access https://github.com/mayswind/AriaNg/issues.
About any other issues or ideas of this extension, you could raise an issue again.
